services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: php -S 0.0.0.0:8080 -t public
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      rabbitmq : { condition: service_healthy }
      mysql : { condition: service_healthy }

  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=slim.messenger
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 5s
      retries: 30

  mysql:
    image: mysql:8.4
    env_file:
      - .env
    volumes:
      - ./docker/mysql/startup:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -u write -pintegration -e 'SELECT 1'"]
      interval: 2s
      timeout: 5s
      retries: 30
