services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: php -S 0.0.0.0:8080 -t public
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      rabbitmq : { condition: service_healthy }

  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=slim.messenger
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 30