
ALTER USER root@'%' IDENTIFIED BY '';

GRANT ALL ON *.* TO root@'%' WITH GRANT OPTION;

CREATE USER 'write'@'%' IDENTIFIED BY 'integration';

GRANT CREATE, DELETE, SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON *.* TO 'write'@'%';

FLUSH PRIVILEGES;